change uid-map to spec-ref-map
cbielow/OpenMS pull request #69
Opened 2019-05-24 11:53 UTC by Waschi97

i would like to work on this PR

2019-05-25 11:09 UTC, cbielow requested changes
nice!

if you want, we could add some verfication code here https://github.com/cbielow/OpenMS/blob/develop/src/topp/QualityControl.cpp#L303
do make sure the mapping targeted all PepIDs in the consensusMap, i.e. all PepIds should carry the metavalue "missed_cleavages" or something which we can guarantee to be present. We can also add it later though

2019-05-25 11:09 UTC, cbielow commented on src/topp/QualityControl.cpp
> +          OPENMS_LOG_ERROR << "FeatureXML (MS run '" << unique_run_path[0] << "') does not correspond to ConsensusXML (run not found). Check input!\n";
you can use `ListUtils::concatenate(x, ", ")` to show the whole StringList

2019-05-25 11:09 UTC, cbielow commented on src/topp/QualityControl.cpp
> +      if (filenames.empty())
check for empty can be done once and earlier (when creating the `identifier_to_prot` map)

2019-05-25 11:09 UTC, cbielow commented on src/topp/QualityControl.cpp
> +      else
use `else if ...`

2019-05-25 11:09 UTC, cbielow commented on src/topp/QualityControl.cpp
> +        continue;
remove the the `continue` and use `else if `

2019-05-25 11:09 UTC, cbielow commented on src/topp/QualityControl.cpp
> +        pep_id.setMetaValue("cf_id", group_id);
this is duplicated in both if-blocks. Move it outside.

2019-05-28 14:14 UTC, Waschi97 commented
> nice!
> 
> if you want, we could add some verfication code here https://github.com/cbielow/OpenMS/blob/develop/src/topp/QualityControl.cpp#L303
> do make sure the mapping targeted all PepIDs in the consensusMap, i.e. all PepIds should carry the metavalue "missed_cleavages" or something which we can guarantee to be present. We can also add it later though

what do you mean by "verification code"? i think i'm not familiar with that..

2019-05-29 07:57 UTC, merged